# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-12 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='author',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='text',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
